[versions]
minecraft     = "26.2"
fabric-loader = "0.19.3"
fabric-api    = "0.152.1+26.2"
fabric-kotlin = "1.13.12+kotlin.2.4.0"
keybinds      = "0.5.0+26.2"
yacl          = "3.9.4+26.2-fabric"

# Compatability
mod-menu      = "20.0.0-beta.2"
carpet        = "26.2"
chunk-debug   = "2.8.0+26.2"
sodium        = "mc26.2-0.9.0-fabric"

# Runtime
dev-auth      = "1.2.2"

# Plugins
fabric-loom   = "1.17-SNAPSHOT"
mod-publish   = "1.1.0"

[libraries]
minecraft     = { module = "com.mojang:minecraft"                    , version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader"              , version.ref = "fabric-loader" }
fabric-api    = { module = "net.fabricmc.fabric-api:fabric-api"      , version.ref = "fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin"     , version.ref = "fabric-kotlin" }
keybinds      = { module = "me.senseiwells:simple-keybinding-library", version.ref = "keybinds" }
yacl          = { module = "dev.isxander:yet-another-config-lib"     , version.ref = "yacl" }

# Compatability
mod-menu      = { module = "com.terraformersmc:modmenu"              , version.ref = "mod-menu" }
carpet        = { module = "com.github.gnembon:fabric-carpet"        , version.ref = "carpet" }
chunk-debug   = { module = "me.senseiwells:chunk-debug"              , version.ref = "chunk-debug" }
sodium        = { module = "maven.modrinth:sodium"                   , version.ref = "sodium" }

# Runtime
dev-auth      = { module = "me.djtheredstoner:DevAuth-fabric"        , version.ref = "dev-auth" }

[plugins]
fabric-loom   = { id = "net.fabricmc.fabric-loom"                    , version.ref = "fabric-loom" }
mod-publish   = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }
