[versions]
minecraft     = "26.1"
fabric-loader = "0.18.4"
fabric-api    = "0.144.0+26.1"
parchment     = "1.21.10:2025.10.12"
fabric-kotlin = "1.13.9+kotlin.2.3.10"
keybinds      = "0.3.0+26.1"
yacl          = "3.9.0+26.1-fabric"

# Compatability
mod-menu      = "18.0.0-alpha.6"
carpet        = "26.1-beta-9"
chunk-debug   = "2.7.0+26.1"
sodium        = "mc26.1-0.8.7-fabric"

# Runtime
dev-auth      = "1.2.2"

# Plugins
fabric-loom   = "1.14-SNAPSHOT"
mod-publish   = "1.1.0"

[libraries]
minecraft     = { module = "com.mojang:minecraft"                    , version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader"              , version.ref = "fabric-loader" }
fabric-api    = { module = "net.fabricmc.fabric-api:fabric-api"      , version.ref = "fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin"     , version.ref = "fabric-kotlin" }
keybinds      = { module = "me.senseiwells:simple-keybinding-library", version.ref = "keybinds" }
yacl          = { module = "dev.isxander:yet-another-config-lib"     , version.ref = "yacl" }

# Compatability
mod-menu      = { module = "com.terraformersmc:modmenu"              , version.ref = "mod-menu" }
carpet        = { module = "com.github.gnembon:fabric-carpet"        , version.ref = "carpet" }
chunk-debug   = { module = "me.senseiwells:chunk-debug"              , version.ref = "chunk-debug" }
sodium        = { module = "maven.modrinth:sodium"                   , version.ref = "sodium" }

# Runtime
dev-auth      = { module = "me.djtheredstoner:DevAuth-fabric"        , version.ref = "dev-auth" }

[plugins]
fabric-loom   = { id = "net.fabricmc.fabric-loom"                    , version.ref = "fabric-loom" }
mod-publish   = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }
